volumes:
  airflow_postgres_data:
  vector_postgres_data:
  mysql_data:
  airflow-data:

x-airflow-common:
  &airflow-common
  image: apache/airflow:latest
  environment:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW__WEBSERVER__RBAC=True
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW__WEBSERVER__COOKIE_SECURE=False
    - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
    - AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True
    - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=600
    - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
    - AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS=True
  volumes:
    - ./dag:/opt/airflow/dags
    - ./airflow-data:/var/lib/airflow
    
    - ./:/opt/airflow/code
  depends_on:
    airflow-db:
      condition: service_healthy
  env_file:
    - ./airflow.env

services:
  airflow-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./airflow.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username mlteam \
          --firstname ML \
          --lastname Team \
          --email ml@example.com \
          --role Admin \
          --password cs6316
    env_file:
      - ./airflow.env

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    env_file:
      - ./airflow.env

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
    env_file:
      - ./airflow.env

  vector_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mlteam
      POSTGRES_PASSWORD: mlteam
      POSTGRES_DB: cs_research_vectordb
    ports:
      - "5430:5430"
    volumes:
      - vector_postgres_data:/var/lib/postgresql/data

  mysql_db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cs_research_db
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mysql_db
      - airflow-db
      - vector_db

